name: HRMS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install
 
      - name: Run backend tests
        working-directory: ./backend
        run: npm test

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 

      - name: Install frontend deps
        working-directory: ./frontend
        run: npm install

      - name: Start React app
        working-directory: ./frontend
         env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm start > react.log 2>&1 &
          sleep 60

      - name: Check React log
        working-directory: ./frontend
        run: cat react.log

      - name: Install Playwright browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./frontend
        run: npx playwright test